{% set name = "trove-classifiers" %}
{% set version = "2024.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trove-classifiers-{{ version }}.tar.gz
  sha256: df7edff9c67ff86b733628998330b180e81d125b1e096536d83ac0fd79673fdc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - calver
    - pip
    - setuptools
  run:
    - python >=3.7

test:
  imports:
    - trove_classifiers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pypa/trove-classifiers
  summary: Canonical source for classifiers on PyPI (pypi.org).
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
