{% set name = "trove-classifiers" %}
{% set version = "2025.12.1.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a74f0400524fc83620a9be74a07074b5cbe7594fd4d97fd4c2bfde625fdc1633

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - trove-classifiers = trove_classifiers.__main__:cli

requirements:
  host:
    - python {{ python_min }}
    - calver
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - trove_classifiers
  commands:
    - trove-classifiers --help
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pypa/trove-classifiers
  summary: Canonical source for classifiers on PyPI (pypi.org).
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
